# Header

menu:
  主页: /
  留言: /guest
  归档: /archives

# SubNav
subnav:
  github: 'https://github.com/0031'
  #weibo: '#'
  #rss: '#'
  #zhihu: '#'
  qq: 'tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=396679132'
  #weixin: '#'
  #jianshu: '#'
  #douban: '#'
  mail: 'mailto:0031git@gmail.com'
  #facebook: '#'
  #google: '#'
  #twitter: '#'
  #linkedin: '#'

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: false
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '继续阅读'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: /assets/images/bounty.jpg

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /assets/images/favicon.ico

#你的头像url
avatar: /assets/images/avatar.jpg

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: '0031'

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  Github: https://github.com/
  NodeJS: https://nodejs.org/
  Hexo: https://hexo.io/
  Litten: https://github.com/litten/
  逐梦博客: http://www.deanhan.cn/

aboutme: 0031，真名秦晓春，<br>就读与于重交，赛迪信息实习。<br><br>热爱桌球与跑步，<br/>目前是一枚Java程序猿。<br/><br/>涉世未深，不卑不亢，<br>及时宜自勉，岁月不待人。

post:
  prev: '新篇'
  next: '旧篇'